name: epd
description: e-Paper Display Driver for Raspberry Pi
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  ffi: ^1.2.1
  bcm2835:
    path: ../bcm2835/

dev_dependencies:
  lints: ^2.0.0
