name: clock
description: Sample application of using e-Paper display on Raspberry Pi
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  ffi: 1.2.1
  bcm2835:
    path: ../bcm2835/

dev_dependencies:
  hotreloader: ^3.0.4
  lints: ^2.0.0
