name: demo
description: Base code for demos
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  hotreloader: ^3.0.4
  meta: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
